<?php

declare(strict_types=1);

namespace AppTest\Repository;

use App\Contract\Entity;
use App\Seed\Post as PostSeed;
use AppTest\AbstractDataAccessTest;
use App\Repository\Post as PostRepository;
use App\Entity\Post as PostEntity;

class PostTest extends AbstractDataAccessTest
{

    /**
     * @var \App\Repository\Post PostRepository
     */
    private $PostRepository;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->PostRepository = new PostRepository();

    }

    public function assertPreConditions()
    {
        parent::assertPreConditions(); // TODO: Change the autogenerated stub
        $this->assertTrue(class_exists(PostEntity::class));
        $this->assertTrue(class_exists(PostRepository::class));
        $this->assertTrue(class_exists(PostSeed::class));
    }

    public function testIfReturnIsPostEntityAndSave()
    {
        $this->assertInstanceOf(PostEntity::class, $this->saveData());
    }

    public function testIfReturnIsEntityAndSave()
    {
        $this->assertInstanceOf(Entity::class, $this->saveData());
    }

    public function testIfReturnIsEntityAndUpdate()
    {
        $category = new PostEntity();
        $category->setTitle(PostSeed::$data[3]['title']);
        $category->setContext(PostSeed::$data[3]['context']);
        $category->setId($this->saveData()->getId());
        $category = $this->PostRepository->save($category);
        $this->assertInstanceOf(Entity::class, $category);
    }

    public function testGetById()
    {
        $category = $this->PostRepository->getById($this->saveData()->getId());
        $this->assertInstanceOf(Entity::class, $category);
        $this->assertInstanceOf(PostEntity::class, $category);
    }

    public function testGetAllIfReturnIsArray()
    {
        $this->saveData();
        $category = $this->PostRepository->getAll();
        $this->assertInternalType('array', $category);
    }

    public function testGetOneByIfReturnIsPostEntity()
    {
        $this->saveData();
        $category = $this->PostRepository->getOneBy();
        $this->assertInstanceOf(PostEntity::class, $category);
    }

    public function testIfReturnIsPostRepository()
    {
        $category = $this->PostRepository->remove($this->saveData()->getId());
        $this->assertInstanceOf(PostRepository::class, $category);
    }

    private function saveData()
    {
        $category = new PostEntity();
        $category->setTitle(PostSeed::$data[1]['title']);
        $category->setContext(PostSeed::$data[1]['context']);
        return $this->PostRepository->save($category);
    }

}